import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

function buildStamp() {
	const now = new Date();
	const pad = (n) => String(n).padStart(2, "0");
	const h = now.getHours();
	const h12 = h % 12 === 0 ? 12 : h % 12;
	return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(
		now.getDate()
	)} ${h12}:${pad(now.getMinutes())} ${h < 12 ? "AM" : "PM"}`;
}

/**
 * `define` values are evaluated once, when the context is created — so in
 * watch mode every rebuild would carry the time the *watcher started*,
 * which is useless for telling which bundle reached a device. Dev builds
 * therefore bake this placeholder and swap it for the real clock reading
 * after each rebuild.
 */
const DEV_STAMP_SENTINEL = "__CALLANDER_DEV_STAMP__";

/** The version being shipped — stable for a given commit, unlike a clock. */
function releaseVersion() {
	return JSON.parse(fs.readFileSync("manifest.json", "utf8")).version;
}

// Dev builds can go straight into a vault's plugin folder so Obsidian
// (and iCloud-synced devices) pick them up. Put the absolute path of the
// vault plugin dir in .vault-plugin-path (gitignored). Production builds
// always output to the repo root (release artifact).
let outDir = ".";
if (!prod && fs.existsSync(".vault-plugin-path")) {
	const target = fs.readFileSync(".vault-plugin-path", "utf8").trim();
	if (target) outDir = target;
}

/**
 * Swap the placeholder for the real clock reading, once per rebuild, so the
 * dev-build notice always names the bundle actually running.
 */
const stampDevBuild = () => {
	if (prod) return;
	const file = path.join(outDir, "main.js");
	if (!fs.existsSync(file)) return;
	const src = fs.readFileSync(file, "utf8");
	if (!src.includes(DEV_STAMP_SENTINEL)) return;
	fs.writeFileSync(file, src.split(DEV_STAMP_SENTINEL).join(buildStamp()));
};

const copyStatics = () => {
	if (outDir === ".") return;
	fs.mkdirSync(outDir, { recursive: true });
	for (const file of ["manifest.json", "styles.css"]) {
		fs.copyFileSync(file, path.join(outDir, file));
	}
	// Hot Reload watches plugin folders containing a .hotreload marker
	const marker = path.join(outDir, ".hotreload");
	if (!fs.existsSync(marker)) fs.writeFileSync(marker, "");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	define: {
		// Baked into the bundle so a running install can say which build it
		// is (surfaced as a dev-only startup notice).
		//
		// Dev gets the build machine's local time, e.g. "2026-08-02 10:39 PM",
		// so you can tell at a glance which bundle reached a device — filled
		// in per rebuild by stampDevBuild(), since a value baked in here
		// would freeze at whenever the watcher started. Release builds MUST
		// stay byte-reproducible — a clock reading would make every rebuild
		// differ and defeat verification — so they carry the manifest
		// version instead, which is fixed for a given tag.
		__CALLANDER_BUILD__: JSON.stringify(
			prod ? releaseVersion() : DEV_STAMP_SENTINEL
		),
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	minify: prod,
	plugins: [
		{
			name: "copy-statics",
			setup(build) {
				build.onEnd(() => {
					stampDevBuild();
					copyStatics();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	// styles.css isn't part of the JS graph — watch it separately so
	// CSS-only edits reach the vault too
	if (outDir !== ".") {
		fs.watch("styles.css", () => {
			try {
				copyStatics();
				console.log("[watch] styles.css copied");
			} catch (e) {
				console.error("styles.css copy failed", e);
			}
		});
	}
	await context.watch();
}
