import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

function buildStamp() {
	const now = new Date();
	const pad = (n) => String(n).padStart(2, "0");
	const h = now.getHours();
	const h12 = h % 12 === 0 ? 12 : h % 12;
	return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(
		now.getDate()
	)} ${h12}:${pad(now.getMinutes())} ${h < 12 ? "AM" : "PM"}`;
}

/**
 * `define` values are evaluated once, when the context is created — so in
 * watch mode every rebuild would carry the time the *watcher started*,
 * which is useless for telling which bundle reached a device. Dev builds
 * therefore bake this placeholder and swap it for the real clock reading
 * after each rebuild.
 */
const DEV_STAMP_SENTINEL = "__CALLANDER_DEV_STAMP__";

/** The version being shipped — stable for a given commit, unlike a clock. */
function releaseVersion() {
	return JSON.parse(fs.readFileSync("manifest.json", "utf8")).version;
}

// Dev builds can go straight into a vault's plugin folder so Obsidian
// (and iCloud-synced devices) pick them up. Put the absolute path of the
// vault plugin dir in .vault-plugin-path (gitignored). Production builds
// always output to the repo root (release artifact).
let outDir = ".";
if (!prod && fs.existsSync(".vault-plugin-path")) {
	const target = fs.readFileSync(".vault-plugin-path", "utf8").trim();
	if (target) outDir = target;
}

/**
 * Swap the placeholder for the real clock reading, once per rebuild, so the
 * dev-build notice always names the bundle actually running.
 */
const stampDevBuild = () => {
	if (prod) return;
	const file = path.join(outDir, "main.js");
	if (!fs.existsSync(file)) return;
	const src = fs.readFileSync(file, "utf8");
	if (!src.includes(DEV_STAMP_SENTINEL)) return;
	fs.writeFileSync(file, src.split(DEV_STAMP_SENTINEL).join(buildStamp()));
};

/** The hand-written stylesheet. `styles.css` at the root is generated. */
const BASE_CSS = path.join("src", "styles", "base.css");

/**
 * Obsidian loads exactly one stylesheet — `styles.css` — so the shipped file
 * is the hand-written base plus whatever the `.module.css` imports compiled
 * to. esbuild emits those next to main.js as `main.css`, which Obsidian would
 * never read, so it's folded in here and the stray file removed.
 *
 * Written to the repo root as well as the vault: the root copy is the release
 * artifact, and the e2e harness copies it into its throwaway vault.
 */
const buildStyles = () => {
	const base = fs.readFileSync(BASE_CSS, "utf8");
	const emitted = path.join(outDir, "main.css");
	let scoped = "";
	if (fs.existsSync(emitted)) {
		scoped = fs.readFileSync(emitted, "utf8");
		fs.rmSync(emitted);
	}
	const css = scoped
		? `${base}\n/* ---- generated from *.module.css — do not edit ---- */\n${scoped}`
		: base;
	fs.writeFileSync("styles.css", css);
	if (outDir !== ".") {
		fs.mkdirSync(outDir, { recursive: true });
		fs.writeFileSync(path.join(outDir, "styles.css"), css);
	}
};

const copyStatics = () => {
	if (outDir === ".") return;
	fs.mkdirSync(outDir, { recursive: true });
	fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
	// Hot Reload watches plugin folders containing a .hotreload marker
	const marker = path.join(outDir, ".hotreload");
	if (!fs.existsSync(marker)) fs.writeFileSync(marker, "");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	define: {
		// Baked into the bundle so a running install can say which build it
		// is (surfaced as a dev-only startup notice).
		//
		// Dev gets the build machine's local time, e.g. "2026-08-02 10:39 PM",
		// so you can tell at a glance which bundle reached a device — filled
		// in per rebuild by stampDevBuild(), since a value baked in here
		// would freeze at whenever the watcher started. Release builds MUST
		// stay byte-reproducible — a clock reading would make every rebuild
		// differ and defeat verification — so they carry the manifest
		// version instead, which is fixed for a given tag.
		__CALLANDER_BUILD__: JSON.stringify(
			prod ? releaseVersion() : DEV_STAMP_SENTINEL
		),
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	// Deliberately NOT plain `minify: prod`. `minifyIdentifiers` also mangles
	// CSS-module class names, and it mangles them hard — `.ExpenseRow_row`
	// becomes `.e`. Those are global selectors in a document shared with
	// every other plugin and theme, so a second plugin minifying its own
	// modules would collide on exactly the same single letters. That's the
	// bug class this whole arrangement exists to remove, so it isn't worth
	// reintroducing at build time.
	//
	// The cost is ~86KB (331KB → 418KB), since the flag stops JS mangling
	// too. Flip both of these back to `minify: prod` to trade it back.
	minifyWhitespace: prod,
	minifySyntax: prod,
	plugins: [
		{
			name: "copy-statics",
			setup(build) {
				build.onEnd(() => {
					stampDevBuild();
					buildStyles();
					copyStatics();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	// The base stylesheet isn't part of the JS graph — watch it separately
	// so CSS-only edits reach the vault too. (Module CSS *is* in the graph,
	// so esbuild rebuilds for those on its own.)
	fs.watch(BASE_CSS, () => {
		try {
			buildStyles();
			console.log("[watch] styles rebuilt");
		} catch (e) {
			console.error("style rebuild failed", e);
		}
	});
	await context.watch();
}
