import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Dev builds can go straight into a vault's plugin folder so Obsidian
// (and iCloud-synced devices) pick them up. Put the absolute path of the
// vault plugin dir in .vault-plugin-path (gitignored). Production builds
// always output to the repo root (release artifact).
let outDir = ".";
if (!prod && fs.existsSync(".vault-plugin-path")) {
	const target = fs.readFileSync(".vault-plugin-path", "utf8").trim();
	if (target) outDir = target;
}

const copyStatics = () => {
	if (outDir === ".") return;
	fs.mkdirSync(outDir, { recursive: true });
	for (const file of ["manifest.json", "styles.css"]) {
		fs.copyFileSync(file, path.join(outDir, file));
	}
	// Hot Reload watches plugin folders containing a .hotreload marker
	const marker = path.join(outDir, ".hotreload");
	if (!fs.existsSync(marker)) fs.writeFileSync(marker, "");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	minify: prod,
	plugins: [
		{
			name: "copy-statics",
			setup(build) {
				build.onEnd(copyStatics);
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	// styles.css isn't part of the JS graph — watch it separately so
	// CSS-only edits reach the vault too
	if (outDir !== ".") {
		fs.watch("styles.css", () => {
			try {
				copyStatics();
				console.log("[watch] styles.css copied");
			} catch (e) {
				console.error("styles.css copy failed", e);
			}
		});
	}
	await context.watch();
}
